### ISSUE TITLE
Logger dosen't return the status whether the log is sent successfully

### ISSUE THREAD

**Issue by conglei** [DataDog/browser-sdk#1040]
When I use `datadogLogs.logger.log()` from `@datadog/browser-logs`. It doesn't return the status if the log is sent successfully.  Is that possible change it to return a `Promise`, so that I can actually capture the error and resend it. Thanks!

**Comment by BenoitZugmeyer** [comment]
You normally don't need to worry about it. For now there is no retry logic but we are currently investigating how to improve reliability when something goes wrong (lack of internet connectivty, intake server failure, ...). So we'll implement a retry logic for you! Does it seems good to you?

**Comment by conglei** [comment]
Thanks @BenoitZugmeyer for the timely response!  So in our use case, some of our log sending logic is trigger by users (i.e., users click a button to send some log back to datadog). For this, we want to make sure that the log is actually sent out successfully. Instead of retuning `void`, it will be great if it can return a promise so we can actually tell users about the status.

**Comment by cjlynch12** [comment]
I would also like to see something similar to the OP proposal so that it's possible to validate/test that the tokens provided during initialization are correct and valid. While a retry method would be handy for network interruptions or temp failures, it doesn't help handle cases where the provided client tokens are invalid (and would just spam invalid requests). Currently, if you provide an invalid `clientToken`, the logger still initializes but request fail with `403`.

e.g:
```
datadogLogs.init({
      clientToken: 'made_up_token_that_is_invalid',
     env:  'develop',
      service: 'foo-service',
      sampleRate: 100
    })
 ```
 
 will initialize but will send requests to  `https://browser-http-intake.logs.datadoghq.com/v1/input/made_up_token_that_is_invalid?...` which result in a `403`.
 
 Having a way to programmatically check that the provided tokens are valid/invalid would be great to have. Having `logger.*` error handling would cover a few cases, or having a `validateToken` or similar handler available on the `datadogLogs.init` config object.

**Comment by bcaudan** [comment]
Given our data sending strategy, it seems unlikely that we will provide this kind of capability.

For the retry logic, as mentioned, it is something that we plan to address ourselves at some point but we intend to keep it under the hood.

@cjlynch12 feel free to open another issue if you want to discuss more about the invalid token use case.
