### ISSUE TITLE
Cookies don't have SameSite Attribute set

### ISSUE THREAD

**Issue by hill** [DataDog/browser-sdk#1052]
Hi there,

I'm trying to integrate `@datadog/browser-rum` (^3.4.1) into my frontend angular application.

I'm seeing this warning appear in Chrome 92.0.4515.159: "Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute"

![Screen Shot 2021-09-15 at 2 34 40 pm](https://user-images.githubusercontent.com/5620045/133371212-3973feac-35e5-4566-9a56-8cc485b35a7b.png)

I can't seem to find any way in the docs to prevent this warning from appearing?

#430 seems related but the cookies they mentioned (`_dd_s` and `dd_rum_test`) are not the ones erroring here:
- `_gcl_au`
- `_mkto_trk`
- `__utmc`
- `__utmz`
- `_gid`
- `_sp_ses.6425`
- `__utma`
- `_ga`
- `_ga_KN80RDFSQK`
- `_sp_id.6425`

Any suggestions on how I can fix this would be appreciated!

**Comment by bcaudan** [comment]
Hi @hill,

Those cookies without `SameSite` attribute are sent with sdk requests because:

- you previously went on the datadog application
- datadog application share the same domain as the domain where we send sdk requests

So this warning is only shown to users that previously went on the datadog application and there is no real issue with it.
The datadog application team is working on having all application cookies with the `SameSite` attribute set but there are some dependencies on other providers.

In the mean time, if you want to prevent this warning to appear, you can update the sdk init with:

```js
sdk.init({
  ..., 
  useAlternateIntakeDomains: true
})
```
 
SDK requests will then be sent to a different domain which will avoid to attach datadog application cookies to them.
For example, with `site: "datadoghq.com"` and `useAlternateIntakeDomains: true`, requests are sent to `browser-intake-datadoghq.com` domain.

You would also then need to update your [content security policy accordingly](https://docs.datadoghq.com/real_user_monitoring/faq/content_security_policy) if any.

**Comment by hill** [comment]
Ah I see thanks so much @bcaudan that works perfectly. Really appreciate your assistance here!
