### ISSUE TITLE
Datadogs CDN Object { reference: null } console error

### ISSUE THREAD

**Issue by shaunsosw** [DataDog/browser-sdk#1083]
When using the browser log collection CDN we have noticed an influx of the error:

```
Object { reference: null }
datadog-logs-v3.js:1:22623
```

Script is linked on pages like follows;

```
 <script async="" src="https://www.datadoghq-browser-agent.com/datadog-logs-v3.js"></script>
```

There doesn't seem to be any specific cause and we are seeing this across a multitude of devices, intermittently. This doesn't seem to cause any issues with the logging on the page, but we see a lot of these in our datadogs log collection.

Please shout if you need anymore information?

**Comment by bcaudan** [comment]
Hello @shaunsosw, 

Since your issue does not seem to be related directly to a SDK behavior but more to understand how those events are generated from your application, would you mind to go through [support](https://www.datadoghq.com/support/)?
It would avoid to publicly share some of your account information.

**Comment by shaunsosw** [comment]
Hi @bcaudan , 

thanks for your response, it does seem to be an error from the CDN script itself, which is implemented as shown in the documentation so thought it may be useful?

I will contact support as suggested. 

Thanks,

Shaun
