### ISSUE TITLE
Documentation around specifically what sampleRate and replaySampleRate configs do

### ISSUE THREAD

**Issue by aethr** [DataDog/browser-sdk#1092]
We're upgrading a project from v2 to v3 of the `@datadog/browser-logs` and `@datadog/browser-rum` packages, and one of the breaking changes is the replacement of `resourceSampleRate` with `replaySampleRate`.

We're opting out of session replay recording by using the `@datadog/browser-rum-slim` package (also poorly documented if I'm being honest), but we still want to capture 100% of resources in RUM, as we use this for monitoring and to ensure we can correlate logs with traces for all back-end requests.

I can't find a clear description anywhere of the migration path for those of us using `resourceSampleRate`, or a description of specifically what is logged with different configurations.

- if I set `sampleRate: 100` will I get RUM resources for every session/view?
- do I need to set `replaySampleRate: 100` to enable resource logging for all sessions?
- is `replaySampleRate` even meaningful if we're using `browser-rum-slim`?

This the last thing blocking us from quite an urgent upgrade due to https://github.com/DataDog/browser-sdk/issues/1022 so any advice would be greatly appreciated.

Thanks!

**Comment by BenoitZugmeyer** [comment]
Hello @aethr, thank you for your feedback. You are right, the documentation around the new `replaySampleRate` option and `browser-rum-slim` package is missing, and we are working on it. Let me answer your questions:

> We're opting out of session replay recording by using the `@datadog/browser-rum-slim` package

Session Replay is "opt-in", it won't start until you explicitly call `.startSessionReplayRecording()`. `rum-slim` is here only to have a smaller bundle by removing the Session Replay code. So you are right to use it, since you don't care about Session Replay, but just so you know using the normal package would send session replays without any action on your part.

> we still want to capture 100% of resources in RUM

Great, that's the default!

> migration path for those of us using `resourceSampleRate`

I understand that it's not ideal right now. Basically, `resourceSampleRate` have been removed, and we wanted to introduce the new `replaySampleRate` for the new billing plans, but the rollout of the new plans have been delayed, hence the missing docs.

>

**Comment by BenoitZugmeyer** [comment]
Hello @aethr. You are right, the documentation around the new `replaySampleRate` option and `browser-rum-slim` package is missing, and we are working on it. Let me answer your questions:

> We're opting out of session replay recording by using the `@datadog/browser-rum-slim` package

Session Replay is "opt-in", it won't start until you explicitly call `.startSessionReplayRecording()`. `rum-slim` is here only to have a smaller bundle by removing the Session Replay code. So you are right to use it, since you don't care about Session Replay, but just so you know using the normal package would not send session replays without any action on your part.

> we still want to capture 100% of resources in RUM

Great, that's the default!

> migration path for those of us using `resourceSampleRate`

I understand that it's not ideal right now. Basically, `resourceSampleRate` have been removed, and we wanted to introduce the new `replaySampleRate` for the new billing plans, but the rollout of the new plans have been delayed, hence the missing docs.

>     * if I set `sampleRate: 100` will I get RUM resources for every session/view?

`samleRate: 100` is the default. This options controls whether or not a session should be created at all. It does not control resource collection, but yes by default all resources will be collected.

> 
>     * do I need to set `replaySampleRate: 100` to enable resource logging for all sessions?

`replaySampleRate: 100` is the default, so you don't need to set it. You can just ignore it for now, an announce will be made when it's ready to be used.

>     * is `replaySampleRate` even meaningful if we're using `browser-rum-slim`?

Yes, future billing plans will also be applicable to the `rum-slim` package.

> 
> Thanks!

Let us know if you have any other question. Sorry for the lack of documentation, we will work on it, and thank you very much for your feedback!

**Comment by aethr** [comment]
Thanks for all the detail @BenoitZugmeyer !

> yes by default all resources will be collected

This was the most important thing for me to understand, thanks for clearing it up.

Happy to close this ticket.
