### ISSUE TITLE
How to catch early errors prior to first setView?

### ISSUE THREAD

**Issue by StreetStrider** [DataDog/browser-sdk#1181]
Hello.
We have a RUM-instrumented application. We `setView` on some level in our application. If we have some error prior to first `setView` it would be completely ignored, as per documentation, because of no data is collected before view is set. But the early errors are real. In the extreme scenario errors in top-level `<script>`s would not be collected, even if datadog RUM is initialized on top of everything. How we can catch those errors with Datadog?

My first attempt was to `setView` early with `location`-based string or even with some stub string. That worked, but that way we lost loading time for `initial_load` in our reports. Since, `initial_load` is a one-timer, we lost a precious point of data. I have no other idea rather than collect errors by hand and load them into an agent via `addError`, but this is quite cumbersome. How would you advice to solve this issue? Or is it out of this API's scope?

**Comment by bcaudan** [comment]
Hello @StreetStrider,

If I understand correctly, you are using `trackViewsManually: true` and your issue is that you have errors happening between `init` and `startView` calls that are not collected, is that it?

If that is it, indeed, we are not starting the collection of events until the first `startView` is called. However, SDK API calls are saved, so you could indeed catch and forward to `addError` errors happening before `startView` yourself.

Collection of events between `init` and `startView` or between SDK load and `init` are features that we would want to have eventually but that are not on our short term priorities for now.

From my understanding of your first attempt, you do an early `startView` but this view is being quickly replaced by another `startView` triggered by your application which then prevent the collection of loading time for the initial view.
A dirty workaround could be to prevent the first `startView` triggered by your application.

**Comment by StreetStrider** [comment]
> If I understand correctly, you are using trackViewsManually: true and your issue is that you have errors that are not collected because they happen between init and startView calls, is that it?

Yes, just so.

In analytic widgets it is quite often to store data events as a plain list. I was searching for something like this in browser-sdk. I saw some buffering in but I was not sure is it extent to errors. It looks like a buffer of _calls_ itself, not data. So calls are stored inside limited buffer, then eventually re-played when the setup is ready to transmit. So, according to your answer, `addError` would be saved as any other call.

> but this view is being quickly replaced by another startView triggered by your application

This may be the root cause.

> A dirty workaround could be to prevent the first startView triggered by your application.

Understood :thinking: , I wouldn't thought of that. I will investigate it. It seemes it would show some time but it would not be correct.

**Comment by bcaudan** [comment]
> So, according to your answer, addError would be saved as any other call.

yes

**Comment by StreetStrider** [comment]
That was informative and helped me a lot to make things clear, thank you for help.
