### ISSUE TITLE
Getting "Converting circular structure to JSON" in React App

### ISSUE THREAD

**Issue by rafaelguinho** [DataDog/browser-sdk#1193]
I'm getting "Converting circular structure to JSON
    --> starting at object with constructor 'XMLHttpRequest'
    |     property '_datadog_xhr' -> object with constructor 'Object'
    --- property 'xhr' closes the circle"

This error ocur after inicialize browser agent and breaks the entire aplication.

**Comment by rafaelguinho** [comment]
I have tried to use NPM module, and CDN sync and async but still the same issue.

**Comment by metasean** [comment]
I'm running into the exact same error in a Nuxt v.2/Vue v.2 app.

**Comment by bcaudan** [comment]
Hello,

I can reproduce by

```js
// init SDK

const xhr = new XMLHttpRequest()
xhr.open('get', 'http://localhost:8080')
xhr.send()

JSON.stringify(xhr)
```

is there any stringification done on xhr on your apps or on the framework you are using? 
or is it something else?

**Comment by rafaelguinho** [comment]
Hello @bcaudan, not in my code,  I'm using React 17.0.1 and axios 0.21.1 for http requests. I did not find any exemple using React on the documentation.

**Comment by metasean** [comment]
Hey @bcaudan - We don't have any in our code and I'm not seeing any in either the @nuxt or @vue module directories.  Like Rafael, we're also using axios, but we're using a slightly more up-to-date version 0.21.4.

**Comment by metasean** [comment]
I've got a bit more info.  I was doing dependency updates when I ran into this, and the Datadog update was a pretty big update (moving up from ^1.26.3).  The only change that I saw in the [changelog](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md) _that looked relevant_ was the removal of `datacenter` from the init.

I've just funneled my way down to the breaking version.  For our app @datadog/browser-rum@v.2.13.0 _works_ while version v.2.14.0 introduces this circular error.  

On the one hand, since v.2.14.0 was released over 6 months ago, I'll be genuinely surprised if other developers haven't already run into this.  On the other hand, in the [v.2.14.0 changelog entry](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v2140) there's an XHR bugfix entry (RUMF-876) which _might_ be related.  Unfortunately, I'm not seeing any stringify usage in there, so this could just be a red herring. 🤷‍♂️

**Comment by bcaudan** [comment]
I am not able to reproduce the issue with a simple integration of RUM + axios:


```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://www.datadoghq-browser-agent.com/datadog-rum-v3.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
      DD_RUM.init({
        clientToken: 'xxx',
        applicationId: 'xxx',
      })
      axios
        .get('/')
        .then(function (response) {
          console.log(response)
        })
        .catch(function (error) {
          console.log(error)
        })
    </script>
  </head>
  <body></body>
</html>
```

Could you provide a minimal setup to reproduce the issue?

**Comment by rafaelguinho** [comment]
@bcaudan using 

`import { datadogRum } from '@datadog/browser-rum';
    
datadogRum.init({
    applicationId: 'xxx',
    clientToken: 'xxx',
    site: 'datadoghq.com',
    service:'dd_rum',
    // Specify a version number to identify the deployed version of your application in Datadog 
    // version: '1.0.0',
    sampleRate: 100,
    trackInteractions: true,
    defaultPrivacyLevel: 'mask-user-input'
});
    
datadogRum.startSessionReplayRecording();`

in the index.js file of a React app.

**Comment by bcaudan** [comment]
@rafaelguinho I have setup a minimal react application with `create-react-app` and initialized RUM as mentioned above in this repository https://github.com/bcaudan/react-app.
I have not seen the circular structure issue.

Could you help me to understand how this issue happen?

**Comment by rafaelguinho** [comment]
@bcaudan It works perfect on localhost, the error occur when I publish it on my server.

**Comment by bcaudan** [comment]
Can you reproduce the behavior on the repository that I have shared?

**Comment by metasean** [comment]
I've narrowed the problem down to https://github.com/DataDog/browser-sdk/blob/main/packages/core/src/browser/xhrObservable.ts#L97 causing a self-referential loop when an error's data is subsequently referenced.  

I'm going to try to put a test together and make a PR.

**Comment by metasean** [comment]
Before adding a test, I went ahead and ran the existing unit and e2e tests.  Unit tests run as expected, but e2e tests are going to be a problem because I've got a current version of Chrome, meanwhile the ChromeDriver will only work with an older version of Chrome:

```
[0-4] 2021-12-08T22:24:57.827Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 94
Current browser version is 96.0.4664.55 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

**Comment by rafaelguinho** [comment]
@bcaudan I found the problem in my code:

```javascript
const client = this.axiosInstance();
const response = await client.get(resource, {
  headers,
});

console.log(JSON.stringify(response));
```

Just change it to use circular-json to convert the response and it worked:

```javascript
import CircularJSON from 'circular-json';

const client = this.axiosInstance();
const response = await client.get(resource, {
  headers,
});

console.log(CircularJSON.stringify(response));
```

**Comment by bcaudan** [comment]
OK since the issue seems related to custom code, it should not be too wide (compared to systematic failure when integrated with a popular lib).
Anyway, as mentioned [here](https://github.com/DataDog/browser-sdk/pull/1204#issuecomment-989762778), we are planning to remove `_datadog_xhr` property in the next major version (probably around january).
We'll keep you posted here.

**Comment by rafaelguinho** [comment]
Thank you @bcaudan

**Comment by bcaudan** [comment]
Thanks for the ping 😉 

With browser-sdk [v4](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#from-v3-to-v4), we have removed `_datadog_xhr` so you should not encounter this issue anymore.
