### ISSUE TITLE
Ability to add all severity levels to browser logs?

### ISSUE THREAD

**Issue by WillSeese** [DataDog/browser-sdk#1208]
My company makes use of the full array of severity levels for logs sent to datadog through http transports, and would like to do so for frontend logs as well, but it appears as though we're limited to error | warn | info | debug by the browser sdk. The integration through the dashboard is read-only so we can't add a status remapper either. Is there a way already built in to do this? If not, I'd like to request that feature.

Thank you

**Comment by bcaudan** [comment]
Hello @WillSeese,

From my understanding, you want to send logs with custom severity, something like:

```js
DD_LOGS.logger.log('hello', {foo: 'bar'}, 'critical')
``` 

For now, our status priority system do not allow that, but it could be improve at some point.

> The integration through the dashboard is read-only so we can't add a status remapper either.

Not sure to see what is your issue here, but indeed you should be able to override log status with another attribute with a remapper.

**Comment by WillSeese** [comment]
Thanks for your response, I received an answer from Cynthia through email that resolved the issue. For anyone else finding this who may be seeking the same behavior, the simple solution is to clone the browser logs pipeline on the dashboard, disable the read-only one, and you can then add a remapper to the clone.
