### ISSUE TITLE
Missing SDK properties in beforeSend hook

### ISSUE THREAD

**Issue by jbardon** [DataDog/browser-sdk#1321]
Hi,
According to the documentation, the SDK adds automatically some properties to each log, such as    
`view.url` and `http.useragent`.

When using the `beforeSend` hook, some of these properties are missing. It seems there are well filled in the end - at least server side - since they're visible in the [log interface](https://app.datadoghq.eu/logs).

### Expected behavior:
In `beforeSend` hook, following properties are available: `view.url`, `view.referrer`, `session_id`, `http.url`, `http.useragent` and `network.client.ip`

### Actual behavior:
In `beforeSend` hook, following properties are available: `view.url`, `view.referrer`,
but others are missing: `session_id`, `http.url`, `http.useragent` and `network.client.ip`

### Reproductible example:
My use case is a company Angular application using the NPM approach but the same issue appear with CDN:
[https://codepen.io/jbardon/pen/BamLxgb?editors=1111
](https://codepen.io/jbardon/pen/BamLxgb?editors=1111
)

I have a legacy apps running the old `logmatic` library that I want to migrate to use `datadog` library. In order to make the migration smoothly and not break existing dashboards, I need to map new properties such as `network.client.ip` to their old name `network.client_ip`.

**Comment by BenoitZugmeyer** [comment]
Hi @jbardon,

Thank you for your thorough report!

* `session_id`: the session is built and stored using cookies. Codepen is using an iframe on a different domain to render the page (as a security mitigation). By default, the Browser SDK uses [same site cookies](https://web.dev/samesite-cookies-explained/), so it fails to create a session (but sessions are optional for logs, so it works nonetheless). Because codepen is using SSL, you can pass [`useCrossSiteSessionCookie: true`](https://docs.datadoghq.com/logs/log_collection/javascript/#initialization-parameters) to `init()` to opt-in to using cross site cookies. The `session_id` property should be set.

* `http.url` is only used when reporting a network error, to indicate the URL of the failed HTTP request (when using the `forwardErrorsToLogs` initialization parameter). It is not provided for normal logs

* `http.useragent` and `network.client.ip` are set by the Datadog backend

To remap some attributes, you should probably create a [Logs pipeline](https://docs.datadoghq.com/logs/log_configuration/pipelines/?tab=source) and use the [Remapper processor](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#remapper).

**Comment by jbardon** [comment]
Thanks for your quick answer 👍 
Lot of details it makes sense to me, your solution looks nice as well.

Maybe the [README](https://github.com/DataDog/browser-sdk/tree/main/packages/logs) for `@datadog/browser-logs` should be updated to make it clear in which situation each parameter is actually set by the SDK. I can do a PR for this if you want to 😄

**Comment by BenoitZugmeyer** [comment]
I made a PR to update it
