### ISSUE TITLE
beforeSend init parameter should always return the same type

### ISSUE THREAD

**Issue by bertold** [DataDog/browser-sdk#1605]
The documented usage of this parameter trips this rule in [SonarQube](https://rules.sonarsource.com/javascript/RSPEC-3800) as it may either return a boolean of `false` to suppress the error or the altered log message.

**Comment by bcaudan** [comment]
Hello @bertold,

Indeed, the `void | false` return type can be a bit confusing but it is how this API has evolved.
We may consider to rework it at some point but this would require a major version since it is a breaking change.
No major version planned for now but we will ping here if we decide to make some progress on this topic.

In the mean time, I would suggest you to ignore this rule for your beforeSend function.

**Comment by bcaudan** [comment]
Hello,

With browser-sdk@5.0.0, we have update the beforeSend signature:

```diff
- beforeSend(event: any, context?: any) => boolean | void
+ beforeSend(event: any, context?: any) => boolean
```

**Nb:** No change on the implementation, if no value is returned, the event is **not** discarded.
