### ISSUE TITLE
how to handle different dev and prod domains in RUM

### ISSUE THREAD

**Issue by dzienisz** [DataDog/browser-sdk#1637]
we use .net domain for dev and stage envs and .com for prod

how to handle this in datadog RUM config

```
datadogRum.init({
        applicationId,
        clientToken,
        version,
        site: 'domain.com', 
        service: 'platform',
        sampleRate: 100,
        trackInteractions: true,
        allowedTracingOrigins: [
          'https://platform.development.domain.net',
          'https://platform.staging.domain.net',
          'https://platform.domain.com',
        ],
      });
```

after updating from 3.1.x to 3.6.x. and 4.x.x we get this error `strict-origin-when-cross-origin`

**Comment by bcaudan** [comment]
Hello @dzienisz,

If I understand correctly, you have tow topics.

1. how to put the right origins in `allowedTracingOrigins` depending on your environment

Depending on how your application is built, you may have a way to know on which environment you are. Then, you could define the configuration according to the current environment.
Otherwise, you may try construct your configuration according to the current `window.location.origin`.

2. After updating the sdk, you get a `strict-origin-when-cross-origin` error
 
Can you provide more details about that?

**Comment by dzienisz** [comment]
2. from network panel, this is POST request

**Request URL:** https://rum.browser-intake-<domain>.com/api/v2/rum?
ddsource=browser
&ddtags=<tags>
&dd-api-key=<key>
&dd-evp-origin-version=<version>
&dd-evp-origin=browser
&dd-request-id=<id>
&batch_time=<number>

**Referrer Policy:** strict-origin-when-cross-origin

**Comment by dzienisz** [comment]
what is **site: 'domain.com', ** and why when I changed it from **datadog.com** to **domain.com** it broken the plugin?

**Comment by bcaudan** [comment]
> 3\. from network panel, this is POST request on https://platform.development.**domain.net**
> 
> **Request URL:** https://rum.browser-intake-**domain.com**/api/v2/rum? ddsource=browser &ddtags= &dd-api-key= &dd-evp-origin-version= &dd-evp-origin=browser &dd-request-id= &batch_time=
> 
> **Referrer Policy:** strict-origin-when-cross-origin

Not sure what to make with that :conf

**Comment by dzienisz** [comment]
Hi, the problem was I changed `site:` to my app domain. I think the documentation does not clearly explain what a `site:` is.

**Comment by bcaudan** [comment]
There was some docs update recently, site parameter point now to [this article](https://docs.datadoghq.com/getting_started/site/), it should hopefully be clearer.

Do you still have an issue?

**Comment by dzienisz** [comment]
No everything is working fine, thanks!
