### ISSUE TITLE
Manifest Version 2 is deprecated!! Error in loading extension

### ISSUE THREAD

**Issue by Iqrah0x01** [DataDog/browser-sdk#1691]
As of January 17, 2022 Chrome Web Store has stopped accepting new Manifest V2 extensions. Kindly update it.
![Screenshot (320)](https://user-images.githubusercontent.com/82658962/184318790-5997cbee-88b9-4075-a800-f86ebf668805.png)

**Comment by BenoitZugmeyer** [comment]
We'll see what we can do about that. It's not as trivial as inscrementing the manifest version because we are using [some blocking webrequest api](https://github.com/DataDog/browser-sdk/blob/014cea7a6d8480b549d10144fe72449214c7c3b2/developer-extension/src/background/domain/replaceBundles.ts#L33).

But to my knowledge, this doesn't prevent you from loading the extension, right?

**Comment by BenoitZugmeyer** [comment]
The extension is now using manifest v3
