### ISSUE TITLE
Possible issues generating X-Ray trace IDs

### ISSUE THREAD

**Issue by willarmiros** [DataDog/browser-sdk#1734]
Hello,

I'm from AWS and some of our systems have been picking up incorrectly formatted X-Ray trace headers on incoming requests. One example malformed trace header we found looked like this:

```
X-Amzn-Trace-Id: Root=1-0-0000000016764bd1ca9d3cc8;Parent=73cb3a63c8208c79;Sampled=1;_dd.origin=rum
```

Per [X-Ray documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader), a normal trace header should look like this (notably the `5759e988` piece MUST be an Epoch timestamp from the last 7 days in hex):

```
X-Amzn-Trace-Id: Root=1-5759e988-bd862e3fe1be46a994272793;Parent=53995c3f42cd8ad8;Sampled=1
```

The trailing `_dd.origin=rum` bit is why I'm opening the issue here, but please feel free to redirect me to a more appropriate place to report this bug. I believe it is causing negative experiences for both AWS and DD customers, would appreciate seeing it fixed :)

**Comment by liywjl** [comment]
Hello @willarmiros,

We do not set `X-Amzn-Trace-Id` in this repo, however I have raised it internally and we are checking where this issue originates from. I suspect it comes from one of the tracing libraries. 

Once we have narrowed it down to a specific repo I will relay the info so you can open an issue there (there are several tracing repos so it is not clear which one is erroneously setting this header). They will likely be able to help resolve this issue.

Thank you again for reporting this.

**Comment by liywjl** [comment]
Hello again @willarmiros,

I think it might be worth raising this issue here https://github.com/DataDog/dd-trace-java as there seems to be a couple areas where X-Ray code is used.

Sorry I could not be of more help, I will mention to the relevant parties about this issue.

**Comment by mcculls** [comment]
Hi @willarmiros 

The Datadog Java tracer currently fills in the epoch timestamp as `00000000` because we don't use that part of the trace header. We do make sure this is formatted properly as 8 hex characters, but we don't ensure it is an
> Epoch timestamp from the last 7 days

Can you point to where this last requirement is defined because I couldn't find it in the docs - all I found was that it is expected to be an epoch timestamp in hex, which `00000000` technically is: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

I'm not sure why this is appearing as `Root=1-0-` in your example, because we always write that part out as ``Root=1-00000000-`, unless something else has reformatted the header?

Anyway, we can easily change the epoch timestamp to meet the `from the last 7 days` requirement. Could you open an issue against https://github.com/DataDog/dd-trace-java to add a non-zero epoch timestamp?

Regarding the trailing text at the end of the header - from my understanding of the `X-Amzn-Trace-Id` spec (from articles such as https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html) it is allowed to have custom fields as long as the main fields are there.

**Comment by willarmiros** [comment]
> Can you point to where this last requirement is defined because I couldn't find it in the docs

It's not the best advertised thing, but we only accept trace updates within 7 days, which is dictated by the trace ID's timestamp: https://docs.aws.amazon.com/general/latest/gr/xray.html#limits_xray

> I'm not sure why this is appearing as Root=1-0- in your example, because we always write that part out as Root=1-00000000-, unless something else has reformatted the header?

This is the big question for us as well. We sometimes also set no-op trace IDs, but those are *all* 0s (e.g. `1-00000000-0000000000000000`), so if you generate with a zero timestamp but a random number then that's a strong reason to think the DD SDK could be where they're coming from. Can you point to the ID generation code?

> Regarding the trailing text at the end of the header

Yep the trailing text is fine - encouraged even as it's the breadcrumb that led me here :)

**Comment by liywjl** [comment]
I am closing this thread as it has been opened elsewhere https://github.com/DataDog/dd-trace-java/issues/3861
