### ISSUE TITLE
🙏 RUM getInternalContext() is undefined

### ISSUE THREAD

**Issue by ryandegruyter** [DataDog/browser-sdk#1976]
**What are you trying to achieve and what is your issue? Please describe.**
I have an Angular app with RUM enabled and it works fine on localhost. 
But once deployed to our S3 + Cloudfront, only for some users, sessions are coming through (also not all of them).

I can never capture any of my sessions, neither can most of my colleagues. 
when I run in the console:

Deployed:
DD_RUM.getInitConfiguration() => it shows the correct configuration.
DD_RUM.getInitialContext() => it returns **undefined**.

Localhost:
DD_RUM.getInitConfiguration() => it shows the correct configuration.
DD_RUM.getInitialContext() => it returns an object with the appid and some extra props.

Any idea what the issue might be?

Also note: when deployed no HTTP requests are made to datadog, no error logs or error requests...

**Describe the solution you'd like**
All sessions are captured

**Comment by amortemousque** [comment]
Hello @ryandegruyter,
Have you any session sample rate applied?
Can you provide more information about your init [configuration]?(https://docs.datadoghq.com/real_user_monitoring/browser/#configuration)

**Comment by ryandegruyter** [comment]
Hi @amortemousque 

- setup is via NPM
- "@datadog/browser-logs": "4.30.1",
- "@datadog/browser-rum": "4.30.1",

Our init code:

 ```
   datadogRum.init({
      applicationId,
      beforeSend: (event, context) => {
        if (!this.production) {
          if (event.type === 'view') {
            event.context = { ...event.context, browserSize: this.getBrowserSize() };
          }
          console.log('before send rum event', { event, context });
        }
      },
      clientToken,
      version,
      site: 'datadoghq.com',
      service,
      env,
      sessionSampleRate: 100,
      sessionReplaySampleRate: 100,
      trackUserInteractions: true,
      trackResources: true,
      trackLongTasks: true,
      defaultPrivacyLevel: DefaultPrivacyLevel.MASK,
    });

    datadogRum.startSessionReplayRecording();
```

**Comment by amortemousque** [comment]
Did you had a look to our [troubleshooting guide](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#missing-data). If not, please do and let me know if you find the solution.

**Comment by ryandegruyter** [comment]
Yep I went through the troubleshooting.

**Comment by ryandegruyter** [comment]
On Safari I do see RUM requests coming through, but getInternalContext is also undefined there.

**Comment by amortemousque** [comment]
Is your app publicly accessible?

**Comment by ryandegruyter** [comment]
@amortemousque , I have a support ticket currently open with datadog, perhaps I can tag you in it and provide you the link to the app there?

**Comment by amortemousque** [comment]
Sure, please do

**Comment by ryandegruyter** [comment]
@amortemousque Could I retrieve your datadoghq email somewhere?

**Comment by amortemousque** [comment]
No worries our support team will do it and we will get back to you

**Comment by ryandegruyter** [comment]
Thanks!

**Comment by dirkkelly** [comment]
This was an issue for us in development because we had sample rate set to 20%. 

After clearing out the `_dd_s` cookie which had `rum=0&...` and setting the sample rate to 100%; we were able to confirm `DD_RUM.getInitialContext()` was populated.

Going forward we've defined a configuration environment variable to ensure that development/staging are always collecting samples.

**Comment by filipehcds** [comment]
Hi @ryandegruyter, @bcaudan, @amortemousque,

Sorry to resurrect this topic, but I am having exactly the same problem. Running locally, everything works fine; however, after deploying to AWS via S3 + CloudFront, the issue arises.

As @ryandegruyter mentioned:

Deployed:
- `DD_RUM.getInitConfiguration()` => it shows the correct configuration.
- `DD_RUM.getInitialContext()` => it returns undefined.

Localhost:
- `DD_RUM.getInitConfiguration()` => it shows the correct configuration.
- `DD_RUM.getInitialContext()` => it returns an object with the app ID and some extra properties.

How did you solve the problem?

Again, sorry to resurrect the topic, but I had a bit of hope since it's exactly the same problem here with our team.

Thank you very much 🙏

**Comment by BenoitZugmeyer** [comment]
@filipehcds if you have any issue with your setup, feel free to contact support@datadoghq.com so you can share more details.

In the meantime, you could try to enable the "debug mode" to investigate your issue. By default, all unexpected errors are hidden, but if you use `_setDebug(true)` the SDK will show them:

```ts
DD_RUM._setDebug(true)
DD_RUM.init(...)
```

This could help you see what is going wrong.
