### ISSUE TITLE
🙏 Does async loading @datadog/browser-rum-slim compromise p50 loading time measurement?

### ISSUE THREAD

**Issue by edwardmyung** [DataDog/browser-sdk#2148]
### **What are you trying to achieve and what is your issue? Please describe.**
I’m currently trying to optimise loading performance, and noticed these two datadog npm packages are significant contributors to the main bundle (they form 16% of the global bundle):

* “@datadog/browser-logs": "^4.34.3"
* "@datadog/browser-rum-slim": "^4.23.1"

What I’ve currently done is:
1. Removed those packages
2. Follow the async installation method for “Browser Logs”
3. Follow the async installation method for “RUM” 

Re: (2) - I’m comfortable about browser-logs being async loaded, as our datadog logging use is quite minimal, and those seem to come through when testing on a QA env

Re: (3) - I’d like to better understand what we’re compromising by async loading RUM. Specifically, I’d like to know:
- Does async loading RUM mean the “P50 initial load” will start measuring from a later point? I.e. give an incorrectly better loading time - as it seems to show a significantly better time when testing this async loading branch on a QA environment
- Does async loading RUM do anything to capture and submit events, similarly to how when async loading [segment.io](http://segment.io/), calls to track events will push events to a queue which is then consumed when the script loads?

### **Describe the solution you'd like**
No solution, just asking to better understand the compromises made when async loading RUM

### **Describe alternatives you've considered**
Not async loading RUM, at the cost of initial load-time

**Comment by bcaudan** [comment]
Hello @edwardmyung,

You can find details in the doc for:

- [differences between the setup](https://docs.datadoghq.com/real_user_monitoring/browser/#choose-the-right-installation-method)
- l[oading time definition](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/#how-loading-time-is-calculated)

> Does async loading RUM mean the “P50 initial load” will start measuring from a later point?

The start point of the measure is always the `navigationStart` of the page.
However, since only the activity occurring after the SDK initialization is taken into account to measure the loading time, depending on your application lifecycle, a change of setup could impact the loading time.

 > Does async loading RUM do anything to capture and , similarly to how when async loading [segment.io](http://segment.io/), calls to track events will push events to a queue which is then consumed when the script loads?

SDK API calls before init are buffered, however, the SDK may miss errors, resources, and user actions triggered before the SDK is initialized.
