### ISSUE TITLE
🐛 sessionReplaySampleRate set to 0 does not turn off session replays

### ISSUE THREAD

**Issue by chris-mo** [DataDog/browser-sdk#2492]
**Describe the bug**
When using version 5.1.0, setting sessionReplaySampleRate to 0 does not prevent session replays from being tracked.

**To Reproduce**
Upgrade to 5.1.0, set sessionReplaySampleRate to 0, and see session replays in dashboard

**Expected behavior**
No session replays should be tracked

**Comment by doichev-ivan** [comment]
Hi there, this issue(or similar) seems to be back in the version 5.14.0
Details:
I was updating version from `4.45.0` to `5.14.0`
It's not reproducible 100%, only for some of sessions after the update
My init configuration:
          sessionSampleRate: 100,
          sessionReplaySampleRate: 0,
          trackUserInteractions: true,
          trackResources: true,
          trackLongTasks: true,
          defaultPrivacyLevel: DefaultPrivacyLevel.MASK_USER_INPUT

Assumption: possibly old cookies related - I have noticed, that `_dd_s` cookie had a `rum=1`, and after I have cleaned up all cookies it became `rum=2` and issue was not reproducible anymore.

Looking forward to hearing your suggestion on resolution.
Meanwhile I will use `startSessionReplayRecordingManually: true` to avoid possible auto replays because of this issue.
Thanks.

**Comment by N-Boutaib** [comment]
Hello @doichev-ivan 
Setting `sessionReplaySampleRate` to `0` should be enough to not start the recording of the session. If you have an active `_dd_s` cookie that holds a state where the session must be recorder. Clearing the cookie (or waiting until its expiry) would be enough.

`startSessionReplayRecordingManually: true` would only allow you to start a session replay if the session is sampled in. With a sample rate of 0, it changes nothing.

**Comment by doichev-ivan** [comment]
Hello @N-Boutaib
Thank you for your answer. 
I believe that it's still an issue, because I can not force our users to cleanup cookies. Waiting until expiry is also not an option because session replays have higher pricing.
I feel that this is a corner case but ideally we would like `sessionReplaySampleRate:0` to always disable session replay and not depend on old cookie or any other local data users could have.
`startSessionReplayRecordingManually: true ` - this setting seems providing expected behaviour with no dependency on cookies
