### ISSUE TITLE
🙏 Inject trace_id and span_id from OpenTelemetry into browser logs

### ISSUE THREAD

**Issue by AdonisLima** [DataDog/browser-sdk#2680]
**What are you trying to achieve and what is your issue? Please describe.**
Is there a way to inject trace_id and span_id  from OpenTelemetry into Browser Logs? I couldn't find it.

**Describe the solution you'd like**
Inject trace_id and span_id into Browser Logs so I can correlate traces and logs using OpenTelemetry traces with automatic instrumentation and Datadog Browser Logs.

**Describe alternatives you've considered**

**Comment by BenoitZugmeyer** [comment]
If I understand correctly, you are using an OpenTelemetry library that generates trace and span ids for every request? Does it provide a way to get those ids in JavaScript?

You should be able to set the `dd.span_id` and `dd.trace_id` properties in logs by doing something like:
```js
logger.info("New request", {
  'dd.trace_id': xxx,
  'dd.span_id': xxx
}) 
```

See the Node.js example [here](https://docs.datadoghq.com/logs/log_configuration/pipelines/?tab=traceid#trace-id-attribute), and see if you can adapt it for your frontend solution.

**Comment by adrianha** [comment]
hi @BenoitZugmeyer , apologize for jump in to this conversation.

Does the injection of traceId and spanId already handled automatically if we use RUM altogether? I mean, RUM will generate traceId and spanId to correlate with APM, wondering how to correlate RUM with Logs, should I inject it manually?

Related with previous question, if I need to handle it manually, currently RUM doesnt have API to get the traceId and spanId, then whats the suggestion to do this?

And, last question is, is it possible to override RUM's internal traceId and spanId? lets say we use OpenTelemetry, similar with OP's, but I want to override RUM's instead of Logs.

Thank you!

**Comment by viktorvsk-dualentry** [comment]
@AdonisLima @adrianha was there a solution to this? Thanks in advance!
