### ISSUE TITLE
stack trace/source mapping for custom action

### ISSUE THREAD

**Issue by b3nb5n** [DataDog/browser-sdk#2703]
Hey! I just got sourcemapping set up for my RUM app and its working great for errors. Is there a way to do the same thing for custom actions? i.e have an unminified stack trace visible in the datadog console for actions tracked via `datadogRum.addAction`

**Comment by N-Boutaib** [comment]
Hello 👋 

Unfortunately, only errors collected by RUM and logs of level `error` collected by browser-logs can be unminified using source maps.

Check more on [the official documentation](https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs).

**Comment by b3nb5n** [comment]
thank you for confirming, are there any workarounds i could try using custom attributes or something similar? If not whats the recommended way of dealing with events with the same name across many different files/locations?

**Comment by amortemousque** [comment]
Hello @b3nb5n,
Could you clarify what you're trying to acheive? 
Basically: 
- if you want to manually collect errors with unminified stack trace you can use [addError](https://docs.datadoghq.com/real_user_monitoring/browser/collecting_browser_errors/?tab=npm#collect-errors-manually)
- for collecting your own view performance timings, you can use the [addTiming](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/#add-your-own-performance-timing) 
- otherwise you can use [addAction](https://docs.datadoghq.com/real_user_monitoring/guide/send-rum-custom-actions/?tab=npm)

**Comment by b3nb5n** [comment]
yeah. basically we're using addAction all over our app to log custom actions, and I'm trying to get a consistent way of finding the exact call site in the source based on the information available on the event in the web console. The problem is that some of our events have names that are used in many different places throughout the app, so running a global search on the codebase shows multiple results. Our current solution is to just include the file name and line number in the event name, but thats too easy to mess up during refactoring or forget all together. Is there an easier/better way to uniquely identify were the actions are actually coming from?

**Comment by cy-moi** [comment]
Hello @b3nb5n ,
To identify where the actions are actually coming from, you can filter them using `view.name`.
Otherwise, if this does not work for you, could you clarify a specific step-by-step use case where the view.name does not lead to the correct location? Plus don't hesitate to contact our [Support Team](https://www.datadoghq.com/support/) for configuration helps.

**Comment by b3nb5n** [comment]
Hi, if there are multiple events in the same view with the same name it could still be ambiguous where the event came from.

**Comment by cy-moi** [comment]
Hi,

Regarding this:

> it could still be ambiguous where the event came from

Could you give us an example (a code piece or implementation steps) of using `addAction()` which lead to this? Maybe we can offer more help from there.
