### ISSUE TITLE
'Cookies not supported' error is reported by library

### ISSUE THREAD

**Issue by jonnywyatt** [DataDog/browser-sdk#288]
The library [console.errors](https://github.com/DataDog/browser-sdk/blob/master/packages/core/src/init.ts#L48) when cookies aren't enabled, which is then sent to Datadog. Could this be a console.info so it doesn't pollute our application's logging?

**Comment by mquentin** [comment]
Hello,
this issue should be fixed with the version 1.7.4 of the SDK.

**Comment by cguirguis** [comment]
@mquentin Hi Maxime, does the library require cookies to work? We have a multi-window application with a shared worker that we'd like to log metrics in, but unfortunately I'm unable to initialize the library due to the fact that the `window` object is not available, and that shared workers don't have access to cookies. Do you have any plans to support logging inside shared workers in the future?
