### ISSUE TITLE
Response undefined in type=resource resource-type=XHR events

### ISSUE THREAD

**Issue by Jony-Y** [DataDog/browser-sdk#2951]
**Describe the bug**
Hi there, we are using the CDN version of the RUM SDK (v5)
`https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js`

We are implementing the `beforeSend` method and wish to enrich our logs with certain response headers. 
Looking at the advanced configurations, we took the example from there
```
if (event.type === 'resource' && event.resource.type === 'fetch') {
            event.context.responseHeaders = Object.fromEntries(context.response.headers)
        }

``` 
This works fine for `fetch` resource-types but, since we make our REST calls with `XMLHttpRequest` (axios) then all of our HTTP calls are `xhr` type, and those have a different contract, where the response object is `undefined`

**To Reproduce**

1.Add the CDN script/SDK to any project
2. Implement the beforeSend method and add 
```
beforeSend: (event, context) => {
        // collect a RUM resource's response headers
        if (event.type === 'resource' && (event.resource.type === 'fetch' || event.resource.type === 'xhr')) {
            event.context.responseHeaders = Object.fromEntries(context.response.headers)
        }
```
3. check console
5. See error

**Expected behavior**
We would expect the xhr response to have the response object and the headers as they do exist and should follow the same contract as `fetch` types or close to it.

**Comment by BenoitZugmeyer** [comment]
[`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) objects are returned by the `fetch` API. This is why we provide the `response` only for `fetch` resources. There is no equivalent when using `XHR`.

Now, there is two workarounds to collect response headers:

### Use [`context.xhr.getAllResponseHeaders`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders)

The XMLHttpRequest object is provided in the context as `context.xhr`. Unfortunately, it's less easy to use than `response.headers` as it just returns a string that you need to parse. Here is how it could look like:

```js
          if (event.type === 'resource') {
            if (event.resource.type === 'xhr') {
              event.context.responseHeaders = Object.fromEntries(
                context.xhr
                  .getAllResponseHeaders()
                  .split(/\r\n/)
                  .map((header) => header.split(': '))
              )
            }
            if (event.resource.type === 'fetch') {
              event.context.responseHeaders = Object.fromEntries(context.response.headers)
            }
          }
        }
```

### Make Axios use `fetch` instead of `xhr`

You can tell Axios to use `fetch` instead of `xhr` by adding the following line somewhere in your app:

```js
axios.defaults.adapter = axios.getAdapter('fetch')
```

See [axios doc](https://axios-http.com/docs/req_config)

**Comment by Jony-Y** [comment]
@BenoitZugmeyer Thanks, I will try. Im not sure if using fetch instead of XMLHttpRequest would affect us in any way, but I will check the two options. 

Thanks for the response
