### ISSUE TITLE
Initializing the DatadogRum on chrome extension (in Iframe) not working

### ISSUE THREAD

**Issue by Igor8757** [DataDog/browser-sdk#798]
Hey, Im working on RUM in different angular applications which include a website and a chrome extension. I followed the guide to initialize the RUM logic in all the clients using this guide:

https://docs.datadoghq.com/real_user_monitoring/browser/
using the npm package in the client. the website seems to work perfectly but the chrome extension always gives me this error : `vendor.js:119504 Cookies are not authorized, we will not send any data.`
and after checking the innerContext after init it returns `undefined`
this is the code that I used in both website and extension with token and app fields being what was generated from DD.

datadogRum.init({
        applicationId: '---',
        clientToken: '---',
        site: 'datadoghq.com',
        service:'---extension',
        sampleRate: 100,
        trackInteractions: true,
        env: environment.production ? 'production' : 'staging',
        allowedTracingOrigins: [/https?:\/\/.*\.--\.com/],
        useCrossSiteSessionCookie: true,
        silentMultipleInit: true
    });
--- is not what is in the code. i changed it from my appId and token here for privacy :D
is there something extra that should be done in the extension or there seems

browser-rum version : 2.7.2

**Comment by bcaudan** [comment]
Hello @Igor8757,

Extension execution context may have some restrictions compared to normal browser execution context.
From the shared error, it seems that the SDK can't successfully set cookies.
Currently, RUM SDK require cookies to store/retrieve session information across the page navigation.

For now, we don't plan to actively support extensions but we plan to work on alternative ways to store session information to support cases where cookies are not allowed.
No ETA yet to share on that front though.

**Comment by abhishekops** [comment]
@bcaudan  May I know any ETA or plans to integrate this feature in any upcoming releases? We plan to integrate RUM for our browser extensions, and don't have any other way to monitor sessions. Thanks

**Comment by bcaudan** [comment]
It is still something that we want to address in the fullness of time, no ETA to share yet though.

**Comment by LuWang1983** [comment]
We've been experienced the same issue on our extension and even on our web app. The internal context returns undefined. We use React and initialize Datadog RUM on component mount at the root level but some users were able to send data, some are not. Is there a more consistent way to set cookie or a way we know for sure that the cookie has been set?

**Comment by BenoitZugmeyer** [comment]
You can check if the cookie has been set by looking at the `getInternalContext()` result. Bear in mind that we don't support webextensions yet, but setuping the SDK into a React Web application should work without issue (except when the user is using an ad blocker extension). Could you open a new issue with more details so we can investigate the issue you are experiencing?

**Comment by LuWang1983** [comment]
Thank you for the prompt response! Absolutely. I will open an issue. I think it has something to do with cookie locking on Chrome.

**Comment by rony-arnac** [comment]
Hi! is there a workaround for making RUM work inside a chrome extension?
also, what is the issue in running it there? 
extensions should have access to cookies. e.g. auth0 stores data on a cookie.
is it maybe the `chrome-extension://` prefix that causes the issue?

**Comment by viclai** [comment]
@BenoitZugmeyer @bcaudan, is there any update on when this might get prioritized?

At the moment, I'm just interested in sending traces from the Chrome extension.  Is there a way to get this working without needing to support everything that RUM provides for a web application?

**Comment by guygrip** [comment]
Hi all,

We've recently documented our journey of enabling logging within Chrome extensions and streaming these logs to Datadog. It provides insights into the unique challenges faced and the solutions we crafted. I think you'll find the solution very cool and easy to implement!

Check it out here: [Enabling Chrome Extension Logging with Datadog: A Journey of Trial and Error <img src=https://github.com/DataDog/browser-sdk/assets/100689713/4025db72-ef84-424d-9c27-5e463df0596c width=400 />](https://eng.grip.security/enabling-chrome-extension-logging-with-datadog-a-journey-of-trial-and-error?utm_source=github)

Any feedback is appreciated. Thanks!

**Comment by abhishekops** [comment]
@guygrip Thanks for putting the effort in documenting your implementation and sharing this writeup. We've gone through the same journey of writing our own logging abstraction for Datadog APIs. However, instead of using `datadog/datadog-api-client`, we've done this by directly calling the APIs ourself. We have some takeaways from your approach. I have one question, does the `atadog-api-client` take care of batching multiple logs on the client side, as with out approach, thats the limitation we came across. Thanks.

**Comment by guygrip** [comment]
> @guygrip Thanks for putting the effort in documenting your implementation and sharing this writeup. We've gone through the same journey of writing our own logging abstraction for Datadog APIs. However, instead of using `datadog/datadog-api-client`, we've done this by directly calling the APIs ourselves. We have some takeaways from your approach. I have one question, does the `atadog-api-client` take care of batching multiple logs on the client side, as with out approach, thats the limitation we came across. Thanks.

That's awesome! Did you also use the client token for sending the logs to the API? Make sure you aren't using your Datadog API key since it's private and shouldn't be exposed to the public.

About logs batching, the API supports sending a batch (list) of logs in one request. We've wrapped it with a simple (~100 lines of code) yet powerful batching mechanism we implemented. 
Generally, instead of sending logs immediately using the API, we are saving them to the storage. Since there are many log calls to the same service worker which run in `async` we used `navigator.locks` as a mutex on logic that saves new logs to the storage. 

Once the log storage reaches a certain limit (let's say 100 logs) we send these logs to Datadog in one request and clear them from the storage.
For cases that we don't reach the log limit, we've added a `chrome.alarms` that runs every few minutes and sends the logs that are currently in the storage and clears it. 

So far, this seems to work great for us :fire:

**Comment by abhishekops** [comment]
>That's awesome! Did you also use the client token for sending the logs to the API? Make sure you aren't using your Datadog API key since it's private and shouldn't be exposed to the public.

That's right, we're using client token as well. 

>About logs batching, the API supports sending a batch (list) of logs in one request. We've wrapped it with a simple (~100 lines of code) yet powerful batching mechanism we implemented.
Generally, instead of sending logs immediately using the API, we are saving them to the storage. Since there are many log calls to the same service worker which run in async we used navigator.locks as a mutex on logic that saves new logs to the storage.

Sounds good. I'll consider using this. There are cases where the extension might get uninstalled, to prevent any such cases or delays in logs, we considered sending them right away. But, these are the improvements I'll consider for the next iteration. 

Thanks a bunch for sharing this though. :) I'll hit up on separately.

**Comment by yannickadam** [comment]
Hi all,

The browser SDK can now be initialised in environments where cookies are not supported by setting the initialization parameter `allowFallbackToLocalStorage: true`. (See [documentation here](https://docs.datadoghq.com/real_user_monitoring/browser/#initialization-parameters))

This should solve the issue from the SDK not initializing in Chrome extensions. If you experience other problems, please open a new issue.
