### ISSUE TITLE
Client Token shown in plain text while using @datadog/browser-rum in our application

### ISSUE THREAD

**Issue by Felistas** [DataDog/browser-sdk#853]
The @datadog/browser-rum displays the client_token in plain text in the url. Shouldn't this be considered a secret or is this by design?

**Comment by BenoitZugmeyer** [comment]
No, the client token and application id are public data. Is it a concern for you?

**Comment by Felistas** [comment]
@BenoitZugmeyer was this by design? An attacker can get hold of the client token and send false information to our dashboard. I understand the client_token has only "write" access.

**Comment by BenoitZugmeyer** [comment]
This is by design, yes. This is similar to the Google Analytics "UA-XXXXX-Y" tracking id. Indeed, a malicious third party may use it to send false information, but the risk should be rather limited.

If you prefer not to disclose the client id, you can use the [`proxyHost` option](https://docs.datadoghq.com/real_user_monitoring/faq/proxy_rum_data/?tab=npm) and store the client token in your backend. Note that it won't prevent malicious third parties to send fake data.

**Comment by Felistas** [comment]
Thanks for the clarification

**Comment by SenorMann** [comment]
Perhaps an option to whitelist domains in the RUM dashboard? @BenoitZugmeyer

**Comment by skandula106** [comment]
I guess datadog doesn't whitelist domains feature, it only whitelists IPs and whitelists domains are referring to email send /receive

**Comment by skandula106** [comment]
Hi @BenoitZugmeyer we are using datadog for capturing user events but the client token was exposing via the browser of its nature how can we prevent this ?

**Comment by skandula106** [comment]
I saw in datadog docs can create a proxy server to prevent this, we created a proxy server and used allowedTracingUrls to add a security layer now also those keys will be available for network requests,

We need to configure domain level restriction in the datadog web level itself, earlier I worked Google Places library we purchased a key for organization use, keys are exposed in network requests of a browser nature but in the GCP we have an option to allow given domains only if the user copied that key he can't do anything because of domain level security configured in GCP.

Do we have like this in Datadog?

**Comment by skandula106** [comment]
> This is by design, yes. This is similar to the Google Analytics "UA-XXXXX-Y" tracking id. Indeed, a malicious third party may use it to send false information, but the risk should be rather limited.
> 
> If you prefer not to disclose the client id, you can use the [`proxyHost` option](https://docs.datadoghq.com/real_user_monitoring/faq/proxy_rum_data/?tab=npm) and store the client token in your backend. Note that it won't prevent malicious third parties to send fake data.

We also use a proxy host but must pass the client token in the datadog browser SDK init level itself, right? @BenoitZugmeyer and in the proxy level also those keys will be shown in the network tab but the datadog URL will be replaced with ours right?

**Comment by skandula106** [comment]
Any update on the request and this enhancement - https://github.com/DataDog/browser-sdk/issues/3236 @BenoitZugmeyer

**Comment by BenoitZugmeyer** [comment]
> We used a proxy host, but we must pass the client token in the datadog browser SDK init level itself, right?

Not necessarily, you can pass any value (ex: `clientToken: "replace-me"`) and then in the proxy you can replace it with the actual token (ex: `url.replace("replace-me", clientToken)`).
 
> here we need to whitelist the domain level itself in the datadog web interface do we have that

No, we don't

> Any update on the request and this enhancement - https://github.com/DataDog/browser-sdk/issues/3236

No update at this point, this is not something we are pursuing right now. I'll let your issue open for now to keep track of your request.

**Comment by skandula106** [comment]
thank you @BenoitZugmeyer
